name: Execute build.sh in CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (if required)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Upgrade pip (if required)
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Step 4: Install dependencies (if required)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: Make build.sh executable
      - name: Make build.sh executable
        run: chmod +x build.sh

      # Step 6: Execute build.sh
      - name: Run build.sh
        run: ./build.sh
